wholeslidedata:
    default:
        yaml_source: 
            training:
            - wsa:
                path: /tmp/TCGA-21-5784-01Z-00-DX1.xml
              wsi:
                path: /tmp/TCGA-21-5784-01Z-00-DX1.tif
        
        image_backend: openslide

        label_map:
            lymphocytes: 3
            
        batch_shape:
            batch_size: 1
            spacing: 0.5
            shape: [256, 256, 3]
        
        annotation_parser:
            hooks:
                - module: wholeslidedata.annotation.hooks
                  attribute: TiledAnnotationHook
                  tile_size: 256
                  ratio: 1   # ratio between spacing in batchshape and spacing level 0 in images
                  label_names: ['lymphocytes']
        
        label_sampler:
            attribute: AnnotationCountedLabelSampler
            annotations_per_label: ${wholeslidedata:dataset.annotations_per_label}
            shuffle: False

        annotation_sampler:
            attribute: OrderedAnnotationSampler
            
        point_sampler:
            attribute: CenterPointSampler
