wholeslidedata:
    default:
        yaml_source: slidingwindowdata.yml
        
        batch_shape:
            batch_size: 1
            shape: [1024, 1024, 3]
            spacing: 0.5
            
        point_sampler:
            attribute: CenterPointSampler
          
        patch_sampler:
            center: True
          
        patch_label_sampler:
            center: True
            spacing: 2.0
            ratio: 4
          