wholeslidedata:
    default:
        yaml_source: data.yml
        seed: 2

        label_map: rumc_label_map-new.yml

        annotation_sources: 
            filters: ['xml']
            
        annotation_parser:
            renamed_labels: label_out.yml

        batch_shape:
            batch_size: 8
            spacing: 0.5
            shape: [8, 8, 3]
            
        label_sampler:
            attribute: OrderedLabelSampler

        annotation_sampler:
            attribute: OrderedAnnotationSampler
            
        point_sampler:
            attribute: UniformPointSampler