wholeslidedata:
    default:
        yaml_source: data.yml
        
        batch_shape:
            batch_size: 10
            spacing: 0.5
            shape: [64, 64, 3]
            
        label_map:
            stroma: 1
            tumor: 2
            lymphocytes: 3

  