wholeslidedata:
    default:
        yaml_source: data.yml
            
        label_map:
            stroma: 1
            tumor: 2
            lymphocytes: 3

        batch_shape:
            batch_size: 8
            spacing: 2.0
            shape: [256, 256, 3]