wholeslidedata:
    default:
        yaml_source:
            training:
                - wsi: 
                    path: /tmp/TCGA-21-5784-01Z-00-DX1.tif
                  wsa: 
                    path: /tmp/TCGA-21-5784-01Z-00-DX1.xml       

        labels:
            stroma: 1
            tumor: 2
            lymphocytes: 3
            
        batch_shape:
            batch_size: 4
            spacing: [0.5, 4.0]
            shape: [[512, 512, 3],[512, 512, 3]]
            y_shape: [2,512,512]
            
        point_sampler:
            "*object": wholeslidedata.samplers.pointsampler.CenterPointSampler