default:
  seed: 123
  tmp_dir: ""
  mode:
    "*object": wholeslidedata.data.mode.create_mode
    name: default
  yaml_source: None
  labels: None
  _labels: 
    "*object": wholeslidedata.annotation.labels._labels_factory
    "*args": ["${labels}"]
  image_backend: ${$wholeslidedata.interoperability.openslide.backend.OpenSlideWholeSlideImageBackend}
  annotation_parser:
    "*object": wholeslidedata.interoperability.asap.parser.AsapAnnotationParser
    labels: ${_labels}
    sample_annotation_types: ["polygon"]
  wsi_file_cls: ${$wholeslidedata.data.files.WholeSlideImageFile}
  wsa_file_cls: ${$wholeslidedata.data.files.WholeSlideAnnotationFile}
  associations:
    "*object": sourcelib.collect.get_associations_from_yaml
    yaml_source: ${yaml_source}
    file_classes:
      wsi: 
        class: ${wsi_file_cls}
        kwargs:
          image_backend: ${image_backend}
      wsa:
        class: ${wsa_file_cls}
        kwargs:
          annotation_parser: ${annotation_parser}
    mode: ${mode}
  dataset: 
    "*object": wholeslidedata.data.dataset.WholeSlideDataSet
    mode: ${mode}
    associations: ${associations} 
    load_images: True
    copy_path: False
  batch_shape:
    "*object": wholeslidedata.samplers.batchshape.BatchShape
    batch_size: None
    spacing: None
    shape: None
  label_sampler_name: BalancedLabelSampler
  label_sampler:
    "*object": wholeslidedata.samplers.labelsampler.${label_sampler_name}
    labels: ${dataset.sample_labels.names}
    seed: ${seed}
  annotation_sampler_name: BalancedAnnotationSampler
  annotation_sampler:
    "*object": wholeslidedata.samplers.annotationsampler.${annotation_sampler_name}
    counts_per_label: ${dataset.annotation_counts_per_label}
    seed: ${seed}
  point_sampler_name: RandomPointSampler
  point_sampler:
    "*object": wholeslidedata.samplers.pointsampler.${point_sampler_name}
    seed: ${seed}
  patch_sampler:
    "*object": wholeslidedata.samplers.patchsampler.PatchSampler
    center: True
    relative: False
  patch_label_sampler_name: SegmentationPatchLabelSampler
  patch_label_sampler:
    "*object": wholeslidedata.samplers.patchlabelsampler.${patch_label_sampler_name}
  sample_callbacks@replace(false):
    - "*object": wholeslidedata.samplers.callbacks.SampleCallback
  sample_sampler: 
    "*object": wholeslidedata.samplers.samplesampler.SampleSampler
    patch_sampler: ${patch_sampler}
    patch_label_sampler: ${patch_label_sampler}
    batch_shape: ${batch_shape}
    sample_callbacks: ${sample_callbacks}
  batch_callbacks@replace(false): 
    - "*object": wholeslidedata.samplers.callbacks.BatchCallback
    - "*object": wholeslidedata.samplers.callbacks.Resolver
      return_dict: False
  batch_reference_sampler:
    "*object": wholeslidedata.samplers.batchreferencesampler.BatchReferenceSampler
    dataset: ${dataset}
    batch_size: ${batch_shape.batch_size}
    label_sampler: ${label_sampler}
    annotation_sampler: ${annotation_sampler}
    point_sampler: ${point_sampler}
  batch_sampler: 
    "*object": wholeslidedata.samplers.batchsampler.BatchSampler
    dataset: ${dataset}
    sampler: ${sample_sampler}
    batch_callbacks: ${batch_callbacks}
        
training:
  mode:
    name: training

validation:
  mode:
    name: validation

test:
  mode:
    name: test

inference:
  mode:
    name: inference
