name: docs

on:
  push:
    branches: [main]
    paths:
      - "wholeslidedata/**"
      - "docs/**"
      - .github/workflows/docs.yml
  pull_request:
    branches: [main]
    paths:
      - "wholeslidedata/**"
      - "docs/**"
      - .github/workflows/docs.yml

env:
  PYTHON_VERSION: "3.8"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        shell: bash
        run: |
          pip install -r ./docs/requirements.txt
      - name: Build the docs
        run: sphinx-build -b html docs/source docs/build/html

      - name: Deploy the documentation on gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
