name: Tests

on:
  workflow_call:

jobs:
  tests:
    strategy:
      matrix:
        python: ["3.8"]
        os: [ubuntu-20.04] # macos-latest, windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Print site packages folder
        shell: bash
        run: |
          python -m site

      - name: Install ASAP
        shell: bash
        run: |
          mkdir -p /home/runner/.local/lib/python3.8/site-packages
          sudo .github/scripts/install_asap.sh

      - name: Install Openslide
        shell: bash
        run: |
          sudo apt-get install -y openslide-tools

      - name: Install dependencies
        shell: bash
        run: |
          pip install -r requirements.txt

      - name: Download data
        shell: bash
        run: |
          python tests/downloaddata.py

      - name: Generate coverage report
        run: |
          pip install pytest pytest-cov coveralls
          cd tests
          pytest -s . --cov --cov-report term-missing

      - name: Upload coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
        shell: bash
        run: |
          pip install coveralls
          cd tests
          coveralls --service=github || echo "!! intermittent coveralls failure"

  coveralls:
    name: Indicate completion to coveralls.io
    needs: tests
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish || echo "!! intermittent coveralls failure"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
